- name: Configure Oramon instances
  hosts:
    - retcon.autostatic.cyso.net
    - backup1.autostatic.cyso.net
  remote_user: ubuntu
  gather_facts: yes
  become: true

  pre_tasks:
  - name: Install Python 2.7
    raw: sudo apt-get install -qq python

  tasks:
    - name: Retrieving the Cyso key
      apt_key:
        url: http://plank.cyso.net/linux/apt.cyso.net.pub.key
        state: present
      environment:
          http_proxy: http://10.181.1.150:8080

    - name: Set the ignore valid for the cyso repo
      get_url:
        url: http://plank.cyso.net/linux/apt.conf.d/00ignorevaliduntil
        dest: /etc/apt/apt.conf.d/00ignorevaliduntil
        mode: 0644
      environment:
          http_proxy: http://10.181.1.150:8080

    - name: Set the tmp remount for the cyso repo
      get_url:
        url: http://plank.cyso.net/linux/apt.conf.d/10tmpremount
        dest: /etc/apt/apt.conf.d/10tmpremount
        mode: 0644
      environment:
          http_proxy: http://10.181.1.150:8080

    - name: Download the xenial cyso mirror
      get_url:
        url: http://plank.cyso.net/linux/sources.list.d/xenial-cyso-mirror.list
        dest: /etc/apt/sources.list.d/xenial-cyso-mirror.list
        mode: 0644
      environment:
          http_proxy: http://10.181.1.150:8080

    - name: Download the xenial repo
      get_url:
        url: http://plank.cyso.net/linux/sources.list.d/xenial-cyso-repo.list
        dest: /etc/apt/sources.list.d/xenial-cyso-repo.list
        mode: 0644
      environment:
          http_proxy: http://10.181.1.150:8080

    - name: Remove the sources.list
      file:
        dest: /etc/apt/sources.list
        state: absent

    - name: Create /etc/apt/apt.conf.d/10proxy
      shell: echo 'Acquire::http::Proxy "http://10.181.1.150:8080";' > /etc/apt/apt.conf.d/10proxy

    - name: Run apt-get dist-upgrade
      apt:
        upgrade: dist
        update_cache: yes

    - name: Create /etc/cyso-overrides.conf
      shell: echo "gethash=no" > /etc/cyso-overrides.conf

    - name: Set full hostname
      shell: echo "$(hostname).autostatic.cyso.net" > /etc/hostname

    - shell: hostname -F /etc/hostname

    - name: Install cyso-key package
      apt:
        name: cyso-key

    - name: Configure timezone
      file:
        dest: /etc/localtime
        state: link
        src: /usr/share/zoneinfo/Europe/Amsterdam

    - command: dpkg-reconfigure -f noninteractive tzdata

